---
fixes:
  - Since we're not waiting for the monitoring to fully go up, we have issues
    with later tasks that run way too fast and the operator is not ready, this
    will make sure it's all good to go before moving forward.
