---
apiVersion: identity.openstack.atmosphere.vexxhost.com/v1alpha1
kind: Role
metadata:
  name: member
  namespace: openstack
---
apiVersion: identity.openstack.atmosphere.vexxhost.com/v1alpha1
kind: Role
metadata:
  name: load-balancer-member
  namespace: openstack
spec:
  roleName: load-balancer_member
---
apiVersion: identity.openstack.atmosphere.vexxhost.com/v1alpha1
kind: ImpliedRole
metadata:
  name: member-implies-load-balancer-member
  namespace: openstack
spec:
  roleRef:
    name: member
  impliedRoleRef:
    name: load-balancer-member
---
apiVersion: atmosphere.vexxhost.com/v1alpha1
kind: Cloud
metadata:
  name: atmosphere
  namespace: openstack
spec: {{ _atmosphere_cloud_spec | combine(atmosphere_cloud_spec, recursive=True) | to_json }}
