---
# .. vim: foldmarker=[[[,]]]:foldmethod=marker

# .. Copyright (C) 2022 VEXXHOST, Inc.
# .. SPDX-License-Identifier: Apache-2.0

# Default variables
# =================

# .. contents:: Sections
#    :local:

# .. envvar:: openstack_exporter_image_repository [[[
#
# OpenStack-exporter container image repository location
openstack_exporter_image_repository: "quay.io/niedbalski"

                                                                   # ]]]
# .. envvar:: openstack_exporter_image_tag [[[
#
# openstack-exporter container image tag
openstack_exporter_image_tag: v1.6.0

                                                                   # ]]]
