---
# .. vim: foldmarker=[[[,]]]:foldmethod=marker

# .. Copyright (C) 2022 VEXXHOST, Inc.
# .. SPDX-License-Identifier: Apache-2.0

# Default variables
# =================

# .. contents:: Sections
#    :local:


# .. envvar:: keepalived_enabled [[[
#
# Enable Keepalived for the Atmosphere cluster.  You can disable this if you
# are forwarding ports directly into the cluster from an external network.
keepalived_enabled: true

                                                                   # ]]]
# .. envvar:: keepalived_password [[[
#
# Keepalived password
keepalived_password: "{{ undef(hint='You must specify a Keepalived password') }}"

                                                                   # ]]]
# .. envvar:: keepalived_vip [[[
#
# Keepalived virtual IP address
keepalived_vip: "{{ undef(hint='You must specify a Keepalived virtual IP address') }}"

                                                                   # ]]]
# .. envvar:: keepalived_interface [[[
#
# Keepalived virtual IP interface
keepalived_interface: "{{ undef(hint='You must specify a Keepalived virtual IP interface') }}"

                                                                   # ]]]
# .. envvar:: keepalived_image_repository [[[
#
# Keepalived container image repository location
keepalived_image_repository: "{{ atmosphere_image_repository | default('us-docker.pkg.dev/vexxhost-infra/openstack') }}"

                                                                   # ]]]
# .. envvar:: keepalived_image_tag [[[
#
# Keepalived container image tag
keepalived_image_tag: 2.0.19

                                                                   # ]]]
# .. envvar:: keepalived_vrid [[[
#
# Keepalived virtual router id
keepalived_vrid: 51

                                                                   # ]]]
