---
# .. vim: foldmarker=[[[,]]]:foldmethod=marker

# .. Copyright (C) 2022 VEXXHOST, Inc.
# .. SPDX-License-Identifier: Apache-2.0

# Default variables
# =================

# .. contents:: Sections
#    :local:


# .. envvar:: cert_manager_acme_server [[[
#
# ACME server URL
cert_manager_acme_server: "{{ lookup('env', 'ATMOSPHERE_ACME_SERVER') | default('https://acme-v02.api.letsencrypt.org/directory', True) }}"

                                                                   # ]]]
# .. envvar:: cert_manager_issuer [[[
#
# Definition for the ``cert-manager`` issuer
cert_manager_issuer:
  acme:
    email: mnaser@vexxhost.com
    server: "{{ cert_manager_acme_server }}"
    privateKeySecretRef:
      name: issuer-account-key
    solvers:
      - http01:
          ingress:
            class: openstack

                                                                   # ]]]
