---
# .. vim: foldmarker=[[[,]]]:foldmethod=marker

# .. Copyright (C) 2022 VEXXHOST, Inc.
# .. SPDX-License-Identifier: Apache-2.0

# Default variables
# =================

# .. contents:: Sections
#    :local:


# .. envvar:: openstack_helm_horizon_chart_repo_name [[[
#
# Helm repository name for the chart.
openstack_helm_horizon_chart_repo_name: openstack-helm

                                                                   # ]]]
# .. envvar:: openstack_helm_horizon_chart_repo_url [[[
#
# Helm repository URL for the chart.
openstack_helm_horizon_chart_repo_url: https://tarballs.opendev.org/openstack/openstack-helm/

                                                                   # ]]]
# .. envvar:: openstack_helm_horizon_chart_name [[[
#
# Helm chart name (will also be used for release name)
openstack_helm_horizon_chart_name: horizon

                                                                   # ]]]
# .. envvar:: openstack_helm_horizon_image_repository [[[
#
# Image repository location to be prefixed for all images
openstack_helm_horizon_image_repository: "{{ atmosphere_image_repository | default('us-docker.pkg.dev/vexxhost-infra/openstack') }}"

                                                                   # ]]]
# .. envvar:: openstack_helm_horizon_image_tag [[[
#
# Image tag for container
openstack_helm_horizon_image_tag: 19.2.1.dev13

                                                                   # ]]]
# .. envvar:: openstack_helm_horizon_heat_image_tag [[[
#
# Image tag for Heat to be used for jobs running via Helm hooks
openstack_helm_horizon_heat_image_tag: wallaby

                                                                   # ]]]
# .. envvar:: openstack_helm_horizon_values [[[
#
# Overrides for Helm chart values
openstack_helm_horizon_values: {}

                                                                   # ]]]
