# Copyright (c) 2022 VEXXHOST, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

kubernetes_repo_url: "{{ _kubernetes_upstream_apt_repository }}"
kubernetes_version: 1.22.7

kubernetes_kernel_modules:
  - br_netfilter

kubernetes_sysctls:
  - name: net.ipv4.ip_forward
    value: 1
  - name: net.ipv4.tcp_l3mdev_accept
    value: 1
  - name: net.ipv4.udp_l3mdev_accept
    value: 1
  - name: net.bridge.bridge-nf-call-iptables
    value: 1
  - name: net.bridge.bridge-nf-call-ip6tables
    value: 1
  - name: net.ipv4.conf.all.rp_filter
    value: 0

kubernetes_control_plane_group: controllers
