---
# .. vim: foldmarker=[[[,]]]:foldmethod=marker

# .. Copyright (C) 2022 VEXXHOST, Inc.
# .. SPDX-License-Identifier: Apache-2.0

# Default variables
# =================

# .. contents:: Sections
#    :local:


# .. envvar:: kubernetes_repo_url [[[
#
# Kubernetes repository URL
kubernetes_repo_url: "{{ _kubernetes_upstream_apt_repository }}"

                                                                   # ]]]
# .. envvar:: kubernetes_version [[[
#
# Kubernetes version
kubernetes_version: 1.22.7

                                                                   # ]]]
# .. envvar:: kubernetes_kernel_modules [[[
#
# List of kernel modules to be automatically loaded
kubernetes_kernel_modules:
  - br_netfilter

                                                                   # ]]]
# .. envvar:: kubernetes_sysctls [[[
#
# List of ``sysctl`` parameters to set
kubernetes_sysctls:
  - name: net.ipv4.ip_forward
    value: 1
  - name: net.ipv4.tcp_l3mdev_accept
    value: 1
  - name: net.ipv4.udp_l3mdev_accept
    value: 1
  - name: net.bridge.bridge-nf-call-iptables
    value: 1
  - name: net.bridge.bridge-nf-call-ip6tables
    value: 1
  - name: net.ipv4.conf.all.rp_filter
    value: 0

                                                                   # ]]]
# .. envvar:: kubernetes_control_plane_group [[[
#
# Name of Ansible group containing all control-plane nodes
kubernetes_control_plane_group: controllers

                                                                   # ]]]
