---
# .. vim: foldmarker=[[[,]]]:foldmethod=marker

# .. Copyright (C) 2022 VEXXHOST, Inc.
# .. SPDX-License-Identifier: Apache-2.0

# Default variables
# =================

# .. contents:: Sections
#    :local:


# .. envvar:: kube_prometheus_stack_values [[[
#
# Overrides for Helm chart values
kube_prometheus_stack_values: {}

                                                                   # ]]]
