name: test-master
'on':
  pull_request: {}
  push:
    branches:
    - main
jobs:
  build-images:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.0.2
    - uses: docker/setup-qemu-action@v2.0.0
    - uses: docker/setup-buildx-action@v2.0.0
    - uses: docker/login-action@v2.0.0
      with:
        registry: quay.io
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_ROBOT_TOKEN }}
    - name: Build openstack/cinder
      uses: docker/build-push-action@v3.1.1
      with:
        context: images/openstack
        cache-from: type=gha,scope=cinder-master
        cache-to: type=gha,mode=max,scope={project}-{release}
        push: true
        platforms: linux/amd64
        build-args: 'RELEASE=master

          PROJECT=cinder

          PROJECT_REF=cf2b3005aa39b5700f51be0140c61ad9f8ec47db

          PROFILES=ceph qemu

          DIST_PACKAGES=

          PIP_PACKAGES='
        tags: quay.io/vexxhost/cinder:cf2b3005aa39b5700f51be0140c61ad9f8ec47db
    - name: Build openstack/heat
      uses: docker/build-push-action@v3.1.1
      with:
        context: images/openstack
        cache-from: type=gha,scope=heat-master
        cache-to: type=gha,mode=max,scope={project}-{release}
        push: true
        platforms: linux/amd64
        build-args: 'RELEASE=master

          PROJECT=heat

          PROJECT_REF=f98d164be9c7fecd390b3e4822b33ad4054fcfca

          PROFILES=

          DIST_PACKAGES=curl

          PIP_PACKAGES='
        tags: quay.io/vexxhost/heat:f98d164be9c7fecd390b3e4822b33ad4054fcfca
    - name: Build openstack/senlin
      uses: docker/build-push-action@v3.1.1
      with:
        context: images/openstack
        cache-from: type=gha,scope=senlin-master
        cache-to: type=gha,mode=max,scope={project}-{release}
        push: true
        platforms: linux/amd64
        build-args: 'RELEASE=master

          PROJECT=senlin

          PROJECT_REF=5d3bc56e01f163b62b6e5d53c53ec1bdcf792cc7

          PROFILES=

          DIST_PACKAGES=

          PIP_PACKAGES='
        tags: quay.io/vexxhost/senlin:5d3bc56e01f163b62b6e5d53c53ec1bdcf792cc7
    - name: Build openstack/octavia
      uses: docker/build-push-action@v3.1.1
      with:
        context: images/openstack
        cache-from: type=gha,scope=octavia-master
        cache-to: type=gha,mode=max,scope={project}-{release}
        push: true
        platforms: linux/amd64
        build-args: 'RELEASE=master

          PROJECT=octavia

          PROJECT_REF=98ec46b8073bda426316235f743e9af004172389

          PROFILES=

          DIST_PACKAGES=

          PIP_PACKAGES='
        tags: quay.io/vexxhost/octavia:98ec46b8073bda426316235f743e9af004172389
    - name: Build openstack/barbican
      uses: docker/build-push-action@v3.1.1
      with:
        context: images/openstack
        cache-from: type=gha,scope=barbican-master
        cache-to: type=gha,mode=max,scope={project}-{release}
        push: true
        platforms: linux/amd64
        build-args: 'RELEASE=master

          PROJECT=barbican

          PROJECT_REF=ff7fef62116bf5e128da1207752fb69a6193e606

          PROFILES=

          DIST_PACKAGES=

          PIP_PACKAGES='
        tags: quay.io/vexxhost/barbican:ff7fef62116bf5e128da1207752fb69a6193e606
    - name: Build openstack/designate
      uses: docker/build-push-action@v3.1.1
      with:
        context: images/openstack
        cache-from: type=gha,scope=designate-master
        cache-to: type=gha,mode=max,scope={project}-{release}
        push: true
        platforms: linux/amd64
        build-args: 'RELEASE=master

          PROJECT=designate

          PROJECT_REF=927e34ee5a53771530e78bcbbd74549c632b539a

          PROFILES=

          DIST_PACKAGES=bind9utils

          PIP_PACKAGES='
        tags: quay.io/vexxhost/designate:927e34ee5a53771530e78bcbbd74549c632b539a
    - name: Build openstack/nova
      uses: docker/build-push-action@v3.1.1
      with:
        context: images/openstack
        cache-from: type=gha,scope=nova-master
        cache-to: type=gha,mode=max,scope={project}-{release}
        push: true
        platforms: linux/amd64,linux/arm64
        build-args: 'RELEASE=master

          PROJECT=nova

          PROJECT_REF=69bc4c38d1c5b98fcbbe8b16a7dfeb654e3b8173

          PROFILES=ceph openvswitch configdrive qemu migration

          DIST_PACKAGES=ovmf qemu-efi-aarch64

          PIP_PACKAGES='
        tags: quay.io/vexxhost/nova:69bc4c38d1c5b98fcbbe8b16a7dfeb654e3b8173
    - name: Build openstack/neutron
      uses: docker/build-push-action@v3.1.1
      with:
        context: images/openstack
        cache-from: type=gha,scope=neutron-master
        cache-to: type=gha,mode=max,scope={project}-{release}
        push: true
        platforms: linux/amd64,linux/arm64
        build-args: 'RELEASE=master

          PROJECT=neutron

          PROJECT_REF=3e8f2325d626a695a812a093907a6f3fd2e1315f

          PROFILES=openvswitch vpn

          DIST_PACKAGES=jq ethtool lshw

          PIP_PACKAGES=neutron-vpnaas'
        tags: quay.io/vexxhost/neutron:3e8f2325d626a695a812a093907a6f3fd2e1315f
    - name: Build openstack/monasca-notification
      uses: docker/build-push-action@v3.1.1
      with:
        context: images/openstack
        cache-from: type=gha,scope=monasca-notification-master
        cache-to: type=gha,mode=max,scope={project}-{release}
        push: true
        platforms: linux/amd64
        build-args: 'RELEASE=master

          PROJECT=monasca-notification

          PROJECT_REF=5225304a268fbd7e5edc30ab6d2b0cbf3b92b565

          PROFILES=

          DIST_PACKAGES=

          PIP_PACKAGES='
        tags: quay.io/vexxhost/monasca-notification:5225304a268fbd7e5edc30ab6d2b0cbf3b92b565
    - name: Build openstack/monasca-agent
      uses: docker/build-push-action@v3.1.1
      with:
        context: images/openstack
        cache-from: type=gha,scope=monasca-agent-master
        cache-to: type=gha,mode=max,scope={project}-{release}
        push: true
        platforms: linux/amd64
        build-args: 'RELEASE=master

          PROJECT=monasca-agent

          PROJECT_REF=29be6e96a6c590221e7d2fd1e30dffc7aec519a9

          PROFILES=

          DIST_PACKAGES=iproute2 libvirt-clients lshw

          PIP_PACKAGES=libvirt-python python-glanceclient python-neutronclient python-novaclient
          py3nvml'
        tags: quay.io/vexxhost/monasca-agent:29be6e96a6c590221e7d2fd1e30dffc7aec519a9
    - name: Build openstack/keystone
      uses: docker/build-push-action@v3.1.1
      with:
        context: images/openstack
        cache-from: type=gha,scope=keystone-master
        cache-to: type=gha,mode=max,scope={project}-{release}
        push: true
        platforms: linux/amd64
        build-args: 'RELEASE=master

          PROJECT=keystone

          PROJECT_REF=1dd6993d7b9b647810e6f495b62c37627c6e8658

          PROFILES=apache ldap openidc

          DIST_PACKAGES=

          PIP_PACKAGES='
        tags: quay.io/vexxhost/keystone:1dd6993d7b9b647810e6f495b62c37627c6e8658
    - name: Build openstack/horizon
      uses: docker/build-push-action@v3.1.1
      with:
        context: images/openstack
        cache-from: type=gha,scope=horizon-master
        cache-to: type=gha,mode=max,scope={project}-{release}
        push: true
        platforms: linux/amd64
        build-args: 'RELEASE=master

          PROJECT=horizon

          PROJECT_REF=857d17467adca804fab70c0d8a88f2bf89234ae5

          PROFILES=apache

          DIST_PACKAGES=

          PIP_PACKAGES=designate-dashboard heat-dashboard ironic-ui magnum-ui neutron-vpnaas-dashboard
          octavia-dashboard senlin-dashboard monasca-ui'
        tags: quay.io/vexxhost/horizon:857d17467adca804fab70c0d8a88f2bf89234ae5
    - name: Build openstack/monasca-api
      uses: docker/build-push-action@v3.1.1
      with:
        context: images/openstack
        cache-from: type=gha,scope=monasca-api-master
        cache-to: type=gha,mode=max,scope={project}-{release}
        push: true
        platforms: linux/amd64
        build-args: 'RELEASE=master

          PROJECT=monasca-api

          PROJECT_REF=658c68b593a4d83f59143dc6c7df81860d3f57cb

          PROFILES=apache influxdb

          DIST_PACKAGES=

          PIP_PACKAGES='
        tags: quay.io/vexxhost/monasca-api:658c68b593a4d83f59143dc6c7df81860d3f57cb
    - name: Build openstack/ironic
      uses: docker/build-push-action@v3.1.1
      with:
        context: images/openstack
        cache-from: type=gha,scope=ironic-master
        cache-to: type=gha,mode=max,scope={project}-{release}
        push: true
        platforms: linux/amd64
        build-args: 'RELEASE=master

          PROJECT=ironic

          PROJECT_REF=4a347b3069498d0f2b49105014e6e118b5972c0f

          PROFILES=ipxe ipmi qemu tftp

          DIST_PACKAGES=ethtool lshw iproute2

          PIP_PACKAGES=python-dracclient sushy'
        tags: quay.io/vexxhost/ironic:4a347b3069498d0f2b49105014e6e118b5972c0f
    - name: Build openstack/glance
      uses: docker/build-push-action@v3.1.1
      with:
        context: images/openstack
        cache-from: type=gha,scope=glance-master
        cache-to: type=gha,mode=max,scope={project}-{release}
        push: true
        platforms: linux/amd64
        build-args: 'RELEASE=master

          PROJECT=glance

          PROJECT_REF=cb60c1d2facde2f318ec30c8b9cf63844eaccf92

          PROFILES=ceph

          DIST_PACKAGES=

          PIP_PACKAGES='
        tags: quay.io/vexxhost/glance:cb60c1d2facde2f318ec30c8b9cf63844eaccf92
    - name: Build openstack/magnum
      uses: docker/build-push-action@v3.1.1
      with:
        context: images/openstack
        cache-from: type=gha,scope=magnum-master
        cache-to: type=gha,mode=max,scope={project}-{release}
        push: true
        platforms: linux/amd64
        build-args: 'RELEASE=master

          PROJECT=magnum

          PROJECT_REF=60b338126601be3db42ba65d71649c4e3878b4f3

          PROFILES=

          DIST_PACKAGES=

          PIP_PACKAGES='
        tags: quay.io/vexxhost/magnum:60b338126601be3db42ba65d71649c4e3878b4f3
    - name: Build openstack/monasca-persister
      uses: docker/build-push-action@v3.1.1
      with:
        context: images/openstack
        cache-from: type=gha,scope=monasca-persister-master
        cache-to: type=gha,mode=max,scope={project}-{release}
        push: true
        platforms: linux/amd64
        build-args: 'RELEASE=master

          PROJECT=monasca-persister

          PROJECT_REF=1ea4e21eb231e4fe193e62f1b03b957c9d4281c8

          PROFILES=influxdb

          DIST_PACKAGES=

          PIP_PACKAGES='
        tags: quay.io/vexxhost/monasca-persister:1ea4e21eb231e4fe193e62f1b03b957c9d4281c8
    - name: Build openstack/placement
      uses: docker/build-push-action@v3.1.1
      with:
        context: images/openstack
        cache-from: type=gha,scope=placement-master
        cache-to: type=gha,mode=max,scope={project}-{release}
        push: true
        platforms: linux/amd64
        build-args: 'RELEASE=master

          PROJECT=placement

          PROJECT_REF=d0e05e89ac4a57b6489007ed46e86357f11e5b23

          PROFILES=apache

          DIST_PACKAGES=

          PIP_PACKAGES=httplib2'
        tags: quay.io/vexxhost/placement:d0e05e89ac4a57b6489007ed46e86357f11e5b23
    - name: Promote openstack/cinder
      uses: akhilerm/tag-push-action@v2.0.0
      with:
        src: quay.io/vexxhost/cinder:cf2b3005aa39b5700f51be0140c61ad9f8ec47db
        dst: quay.io/vexxhost/cinder:master
    - name: Promote openstack/heat
      uses: akhilerm/tag-push-action@v2.0.0
      with:
        src: quay.io/vexxhost/heat:f98d164be9c7fecd390b3e4822b33ad4054fcfca
        dst: quay.io/vexxhost/heat:master
    - name: Promote openstack/senlin
      uses: akhilerm/tag-push-action@v2.0.0
      with:
        src: quay.io/vexxhost/senlin:5d3bc56e01f163b62b6e5d53c53ec1bdcf792cc7
        dst: quay.io/vexxhost/senlin:master
    - name: Promote openstack/octavia
      uses: akhilerm/tag-push-action@v2.0.0
      with:
        src: quay.io/vexxhost/octavia:98ec46b8073bda426316235f743e9af004172389
        dst: quay.io/vexxhost/octavia:master
    - name: Promote openstack/barbican
      uses: akhilerm/tag-push-action@v2.0.0
      with:
        src: quay.io/vexxhost/barbican:ff7fef62116bf5e128da1207752fb69a6193e606
        dst: quay.io/vexxhost/barbican:master
    - name: Promote openstack/designate
      uses: akhilerm/tag-push-action@v2.0.0
      with:
        src: quay.io/vexxhost/designate:927e34ee5a53771530e78bcbbd74549c632b539a
        dst: quay.io/vexxhost/designate:master
    - name: Promote openstack/nova
      uses: akhilerm/tag-push-action@v2.0.0
      with:
        src: quay.io/vexxhost/nova:69bc4c38d1c5b98fcbbe8b16a7dfeb654e3b8173
        dst: quay.io/vexxhost/nova:master
    - name: Promote openstack/neutron
      uses: akhilerm/tag-push-action@v2.0.0
      with:
        src: quay.io/vexxhost/neutron:3e8f2325d626a695a812a093907a6f3fd2e1315f
        dst: quay.io/vexxhost/neutron:master
    - name: Promote openstack/monasca-notification
      uses: akhilerm/tag-push-action@v2.0.0
      with:
        src: quay.io/vexxhost/monasca-notification:5225304a268fbd7e5edc30ab6d2b0cbf3b92b565
        dst: quay.io/vexxhost/monasca-notification:master
    - name: Promote openstack/monasca-agent
      uses: akhilerm/tag-push-action@v2.0.0
      with:
        src: quay.io/vexxhost/monasca-agent:29be6e96a6c590221e7d2fd1e30dffc7aec519a9
        dst: quay.io/vexxhost/monasca-agent:master
    - name: Promote openstack/keystone
      uses: akhilerm/tag-push-action@v2.0.0
      with:
        src: quay.io/vexxhost/keystone:1dd6993d7b9b647810e6f495b62c37627c6e8658
        dst: quay.io/vexxhost/keystone:master
    - name: Promote openstack/horizon
      uses: akhilerm/tag-push-action@v2.0.0
      with:
        src: quay.io/vexxhost/horizon:857d17467adca804fab70c0d8a88f2bf89234ae5
        dst: quay.io/vexxhost/horizon:master
    - name: Promote openstack/monasca-api
      uses: akhilerm/tag-push-action@v2.0.0
      with:
        src: quay.io/vexxhost/monasca-api:658c68b593a4d83f59143dc6c7df81860d3f57cb
        dst: quay.io/vexxhost/monasca-api:master
    - name: Promote openstack/ironic
      uses: akhilerm/tag-push-action@v2.0.0
      with:
        src: quay.io/vexxhost/ironic:4a347b3069498d0f2b49105014e6e118b5972c0f
        dst: quay.io/vexxhost/ironic:master
    - name: Promote openstack/glance
      uses: akhilerm/tag-push-action@v2.0.0
      with:
        src: quay.io/vexxhost/glance:cb60c1d2facde2f318ec30c8b9cf63844eaccf92
        dst: quay.io/vexxhost/glance:master
    - name: Promote openstack/magnum
      uses: akhilerm/tag-push-action@v2.0.0
      with:
        src: quay.io/vexxhost/magnum:60b338126601be3db42ba65d71649c4e3878b4f3
        dst: quay.io/vexxhost/magnum:master
    - name: Promote openstack/monasca-persister
      uses: akhilerm/tag-push-action@v2.0.0
      with:
        src: quay.io/vexxhost/monasca-persister:1ea4e21eb231e4fe193e62f1b03b957c9d4281c8
        dst: quay.io/vexxhost/monasca-persister:master
    - name: Promote openstack/placement
      uses: akhilerm/tag-push-action@v2.0.0
      with:
        src: quay.io/vexxhost/placement:d0e05e89ac4a57b6489007ed46e86357f11e5b23
        dst: quay.io/vexxhost/placement:master
