name: test-wallaby
'on':
  pull_request: {}
  push:
    branches:
    - main
jobs:
  build-images:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.0.2
    - uses: docker/setup-qemu-action@v2.0.0
    - uses: docker/setup-buildx-action@v2.0.0
    - name: Build OpenStack Nova
      uses: docker/build-push-action@v3.1.1
      with:
        context: images/openstack
        cache-from: type=registry,ref=quay.io/vexxhost/nova:wallaby
        cache-to: type=inline
        push: true
        platforms: linux/amd64,linux/arm64
        build-args: 'RELEASE=wallaby

          PROJECT=nova

          PROJECT_REF=2f7f4cc0babbda80946d9b56eae8f988b39a4d9d

          PROFILES=ceph openvswitch configdrive qemu migration

          DIST_PACKAGES=ovmf qemu-efi-aarch64

          PIP_PACKAGES='
        tags: quay.io/vexxhost/nova:2f7f4cc0babbda80946d9b56eae8f988b39a4d9d
