name: test-wallaby
'on':
  pull_request: {}
  push:
    branches:
    - main
jobs:
  build-images:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.0.2
    - uses: docker/setup-qemu-action@v2.0.0
    - uses: docker/setup-buildx-action@v2.0.0
    - uses: docker/login-action@v2.0.0
      with:
        registry: quay.io
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_ROBOT_TOKEN }}
    - name: Build openstack/cinder
      uses: docker/build-push-action@v3.1.1
      with:
        context: images/openstack
        cache-from: type=gha
        cache-to: type=gha,mode=max
        push: true
        platforms: linux/amd64
        build-args: 'RELEASE=wallaby

          PROJECT=cinder

          PROJECT_REF=70164132dcc590c944fee36c58e93056a3447142

          PROFILES=ceph qemu

          DIST_PACKAGES=

          PIP_PACKAGES='
        tags: quay.io/vexxhost/cinder:70164132dcc590c944fee36c58e93056a3447142
    - name: Build openstack/heat
      uses: docker/build-push-action@v3.1.1
      with:
        context: images/openstack
        cache-from: type=gha
        cache-to: type=gha,mode=max
        push: true
        platforms: linux/amd64
        build-args: 'RELEASE=wallaby

          PROJECT=heat

          PROJECT_REF=d0e2ded71374cffab41499e75efb81782bf83ffa

          PROFILES=

          DIST_PACKAGES=curl

          PIP_PACKAGES='
        tags: quay.io/vexxhost/heat:d0e2ded71374cffab41499e75efb81782bf83ffa
    - name: Build openstack/senlin
      uses: docker/build-push-action@v3.1.1
      with:
        context: images/openstack
        cache-from: type=gha
        cache-to: type=gha,mode=max
        push: true
        platforms: linux/amd64
        build-args: 'RELEASE=wallaby

          PROJECT=senlin

          PROJECT_REF=ac8245b582376b460a2494ad23ff9e2d83d228cb

          PROFILES=

          DIST_PACKAGES=

          PIP_PACKAGES='
        tags: quay.io/vexxhost/senlin:ac8245b582376b460a2494ad23ff9e2d83d228cb
    - name: Build openstack/octavia
      uses: docker/build-push-action@v3.1.1
      with:
        context: images/openstack
        cache-from: type=gha
        cache-to: type=gha,mode=max
        push: true
        platforms: linux/amd64
        build-args: 'RELEASE=wallaby

          PROJECT=octavia

          PROJECT_REF=8abf181448190ea272225ae4415586cbc0e24c6a

          PROFILES=

          DIST_PACKAGES=

          PIP_PACKAGES='
        tags: quay.io/vexxhost/octavia:8abf181448190ea272225ae4415586cbc0e24c6a
    - name: Build openstack/barbican
      uses: docker/build-push-action@v3.1.1
      with:
        context: images/openstack
        cache-from: type=gha
        cache-to: type=gha,mode=max
        push: true
        platforms: linux/amd64
        build-args: 'RELEASE=wallaby

          PROJECT=barbican

          PROJECT_REF=486e60723f1f635b8e1843bccaf144d85556a9f6

          PROFILES=

          DIST_PACKAGES=

          PIP_PACKAGES='
        tags: quay.io/vexxhost/barbican:486e60723f1f635b8e1843bccaf144d85556a9f6
    - name: Build openstack/designate
      uses: docker/build-push-action@v3.1.1
      with:
        context: images/openstack
        cache-from: type=gha
        cache-to: type=gha,mode=max
        push: true
        platforms: linux/amd64
        build-args: 'RELEASE=wallaby

          PROJECT=designate

          PROJECT_REF=8cef906600117b71903b54c4d7c1e072902f7a46

          PROFILES=

          DIST_PACKAGES=bind9utils

          PIP_PACKAGES='
        tags: quay.io/vexxhost/designate:8cef906600117b71903b54c4d7c1e072902f7a46
    - name: Build openstack/nova
      uses: docker/build-push-action@v3.1.1
      with:
        context: images/openstack
        cache-from: type=gha
        cache-to: type=gha,mode=max
        push: true
        platforms: linux/amd64,linux/arm64
        build-args: 'RELEASE=wallaby

          PROJECT=nova

          PROJECT_REF=2f7f4cc0babbda80946d9b56eae8f988b39a4d9d

          PROFILES=ceph openvswitch configdrive qemu migration

          DIST_PACKAGES=ovmf qemu-efi-aarch64

          PIP_PACKAGES='
        tags: quay.io/vexxhost/nova:2f7f4cc0babbda80946d9b56eae8f988b39a4d9d
    - name: Build openstack/neutron
      uses: docker/build-push-action@v3.1.1
      with:
        context: images/openstack
        cache-from: type=gha
        cache-to: type=gha,mode=max
        push: true
        platforms: linux/amd64,linux/arm64
        build-args: 'RELEASE=wallaby

          PROJECT=neutron

          PROJECT_REF=ce82edb2db9cd0dbc640e1fa709540bfd876bb58

          PROFILES=openvswitch vpn

          DIST_PACKAGES=jq ethtool lshw

          PIP_PACKAGES=neutron-vpnaas'
        tags: quay.io/vexxhost/neutron:ce82edb2db9cd0dbc640e1fa709540bfd876bb58
    - name: Build openstack/monasca-notification
      uses: docker/build-push-action@v3.1.1
      with:
        context: images/openstack
        cache-from: type=gha
        cache-to: type=gha,mode=max
        push: true
        platforms: linux/amd64
        build-args: 'RELEASE=wallaby

          PROJECT=monasca-notification

          PROJECT_REF=b7f87925990f7f816a9b61ed542322d544d30265

          PROFILES=

          DIST_PACKAGES=

          PIP_PACKAGES='
        tags: quay.io/vexxhost/monasca-notification:b7f87925990f7f816a9b61ed542322d544d30265
    - name: Build openstack/monasca-agent
      uses: docker/build-push-action@v3.1.1
      with:
        context: images/openstack
        cache-from: type=gha
        cache-to: type=gha,mode=max
        push: true
        platforms: linux/amd64
        build-args: 'RELEASE=wallaby

          PROJECT=monasca-agent

          PROJECT_REF=8547772515174ec785ba2bb2dcc88965e0b094f9

          PROFILES=

          DIST_PACKAGES=iproute2 libvirt-clients lshw

          PIP_PACKAGES=libvirt-python python-glanceclient python-neutronclient python-novaclient
          py3nvml'
        tags: quay.io/vexxhost/monasca-agent:8547772515174ec785ba2bb2dcc88965e0b094f9
    - name: Build openstack/keystone
      uses: docker/build-push-action@v3.1.1
      with:
        context: images/openstack
        cache-from: type=gha
        cache-to: type=gha,mode=max
        push: true
        platforms: linux/amd64
        build-args: 'RELEASE=wallaby

          PROJECT=keystone

          PROJECT_REF=6c75b657352a86e50e63aec44d28784d8863df99

          PROFILES=apache ldap openidc

          DIST_PACKAGES=

          PIP_PACKAGES='
        tags: quay.io/vexxhost/keystone:6c75b657352a86e50e63aec44d28784d8863df99
    - name: Build openstack/horizon
      uses: docker/build-push-action@v3.1.1
      with:
        context: images/openstack
        cache-from: type=gha
        cache-to: type=gha,mode=max
        push: true
        platforms: linux/amd64
        build-args: 'RELEASE=wallaby

          PROJECT=horizon

          PROJECT_REF=82698aa8901b0533f2e62868fabbf5ef4c36cea0

          PROFILES=apache

          DIST_PACKAGES=

          PIP_PACKAGES=designate-dashboard heat-dashboard ironic-ui magnum-ui neutron-vpnaas-dashboard
          octavia-dashboard senlin-dashboard monasca-ui'
        tags: quay.io/vexxhost/horizon:82698aa8901b0533f2e62868fabbf5ef4c36cea0
    - name: Build openstack/monasca-api
      uses: docker/build-push-action@v3.1.1
      with:
        context: images/openstack
        cache-from: type=gha
        cache-to: type=gha,mode=max
        push: true
        platforms: linux/amd64
        build-args: 'RELEASE=wallaby

          PROJECT=monasca-api

          PROJECT_REF=6a18732f771dd299b9375ad0cf56aacfc0d1d156

          PROFILES=apache influxdb

          DIST_PACKAGES=

          PIP_PACKAGES='
        tags: quay.io/vexxhost/monasca-api:6a18732f771dd299b9375ad0cf56aacfc0d1d156
    - name: Build openstack/ironic
      uses: docker/build-push-action@v3.1.1
      with:
        context: images/openstack
        cache-from: type=gha
        cache-to: type=gha,mode=max
        push: true
        platforms: linux/amd64
        build-args: 'RELEASE=wallaby

          PROJECT=ironic

          PROJECT_REF=35e20b62de1a867534d54de844496072ae291eac

          PROFILES=ipxe ipmi qemu tftp

          DIST_PACKAGES=ethtool lshw iproute2

          PIP_PACKAGES=python-dracclient sushy'
        tags: quay.io/vexxhost/ironic:35e20b62de1a867534d54de844496072ae291eac
    - name: Build openstack/glance
      uses: docker/build-push-action@v3.1.1
      with:
        context: images/openstack
        cache-from: type=gha
        cache-to: type=gha,mode=max
        push: true
        platforms: linux/amd64
        build-args: 'RELEASE=wallaby

          PROJECT=glance

          PROJECT_REF=677c89c23631e9083261a1a18ed438d8966e0de2

          PROFILES=ceph

          DIST_PACKAGES=

          PIP_PACKAGES='
        tags: quay.io/vexxhost/glance:677c89c23631e9083261a1a18ed438d8966e0de2
    - name: Build openstack/magnum
      uses: docker/build-push-action@v3.1.1
      with:
        context: images/openstack
        cache-from: type=gha
        cache-to: type=gha,mode=max
        push: true
        platforms: linux/amd64
        build-args: 'RELEASE=wallaby

          PROJECT=magnum

          PROJECT_REF=a35f48e4357bf5f2601fbdaf62d2074719db1dd9

          PROFILES=

          DIST_PACKAGES=

          PIP_PACKAGES='
        tags: quay.io/vexxhost/magnum:a35f48e4357bf5f2601fbdaf62d2074719db1dd9
    - name: Build openstack/monasca-persister
      uses: docker/build-push-action@v3.1.1
      with:
        context: images/openstack
        cache-from: type=gha
        cache-to: type=gha,mode=max
        push: true
        platforms: linux/amd64
        build-args: 'RELEASE=wallaby

          PROJECT=monasca-persister

          PROJECT_REF=0d1cdd567ab030266d59240b80ee405d5a123fbc

          PROFILES=influxdb

          DIST_PACKAGES=

          PIP_PACKAGES='
        tags: quay.io/vexxhost/monasca-persister:0d1cdd567ab030266d59240b80ee405d5a123fbc
    - name: Build openstack/placement
      uses: docker/build-push-action@v3.1.1
      with:
        context: images/openstack
        cache-from: type=gha
        cache-to: type=gha,mode=max
        push: true
        platforms: linux/amd64
        build-args: 'RELEASE=wallaby

          PROJECT=placement

          PROJECT_REF=716b947c479e36ce2e9ec6d9e0bbab882f391892

          PROFILES=apache

          DIST_PACKAGES=

          PIP_PACKAGES=httplib2'
        tags: quay.io/vexxhost/placement:716b947c479e36ce2e9ec6d9e0bbab882f391892
