name: test-xena
'on':
  pull_request: {}
  push:
    branches:
    - main
jobs:
  build-images:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.0.2
    - uses: docker/setup-qemu-action@v2.0.0
    - uses: docker/setup-buildx-action@v2.0.0
    - uses: docker/login-action@v2.0.0
      with:
        registry: quay.io
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_ROBOT_TOKEN }}
    - name: Build openstack/cinder
      uses: docker/build-push-action@v3.1.1
      with:
        context: images/openstack
        cache-from: type=gha,scope=cinder-xena
        cache-to: type=gha,mode=max,scope={project}-{release}
        push: true
        platforms: linux/amd64
        build-args: 'RELEASE=xena

          PROJECT=cinder

          PROJECT_REF=b2caec7696817e02b0763d8b0d4f5d1b7f0b903e

          PROFILES=ceph qemu

          DIST_PACKAGES=

          PIP_PACKAGES='
        tags: quay.io/vexxhost/cinder:b2caec7696817e02b0763d8b0d4f5d1b7f0b903e
    - name: Build openstack/heat
      uses: docker/build-push-action@v3.1.1
      with:
        context: images/openstack
        cache-from: type=gha,scope=heat-xena
        cache-to: type=gha,mode=max,scope={project}-{release}
        push: true
        platforms: linux/amd64
        build-args: 'RELEASE=xena

          PROJECT=heat

          PROJECT_REF=ead7cd61bd685ea46dd21c4ef3ea6b3fde273c10

          PROFILES=

          DIST_PACKAGES=curl

          PIP_PACKAGES='
        tags: quay.io/vexxhost/heat:ead7cd61bd685ea46dd21c4ef3ea6b3fde273c10
    - name: Build openstack/senlin
      uses: docker/build-push-action@v3.1.1
      with:
        context: images/openstack
        cache-from: type=gha,scope=senlin-xena
        cache-to: type=gha,mode=max,scope={project}-{release}
        push: true
        platforms: linux/amd64
        build-args: 'RELEASE=xena

          PROJECT=senlin

          PROJECT_REF=28f8abc29a966d41f8b4502d1fc7432f86b14bea

          PROFILES=

          DIST_PACKAGES=

          PIP_PACKAGES='
        tags: quay.io/vexxhost/senlin:28f8abc29a966d41f8b4502d1fc7432f86b14bea
    - name: Build openstack/octavia
      uses: docker/build-push-action@v3.1.1
      with:
        context: images/openstack
        cache-from: type=gha,scope=octavia-xena
        cache-to: type=gha,mode=max,scope={project}-{release}
        push: true
        platforms: linux/amd64
        build-args: 'RELEASE=xena

          PROJECT=octavia

          PROJECT_REF=bda4d7160aebf7549d72b049c8dca53f7d4dedb5

          PROFILES=

          DIST_PACKAGES=

          PIP_PACKAGES='
        tags: quay.io/vexxhost/octavia:bda4d7160aebf7549d72b049c8dca53f7d4dedb5
    - name: Build openstack/barbican
      uses: docker/build-push-action@v3.1.1
      with:
        context: images/openstack
        cache-from: type=gha,scope=barbican-xena
        cache-to: type=gha,mode=max,scope={project}-{release}
        push: true
        platforms: linux/amd64
        build-args: 'RELEASE=xena

          PROJECT=barbican

          PROJECT_REF=bb2779473f786f3bb7b84bc4f445089da8cbfe88

          PROFILES=

          DIST_PACKAGES=

          PIP_PACKAGES='
        tags: quay.io/vexxhost/barbican:bb2779473f786f3bb7b84bc4f445089da8cbfe88
    - name: Build openstack/designate
      uses: docker/build-push-action@v3.1.1
      with:
        context: images/openstack
        cache-from: type=gha,scope=designate-xena
        cache-to: type=gha,mode=max,scope={project}-{release}
        push: true
        platforms: linux/amd64
        build-args: 'RELEASE=xena

          PROJECT=designate

          PROJECT_REF=410c1e8d60a6b3844050dd4d3ecc46f640356bfb

          PROFILES=

          DIST_PACKAGES=bind9utils

          PIP_PACKAGES='
        tags: quay.io/vexxhost/designate:410c1e8d60a6b3844050dd4d3ecc46f640356bfb
    - name: Build openstack/nova
      uses: docker/build-push-action@v3.1.1
      with:
        context: images/openstack
        cache-from: type=gha,scope=nova-xena
        cache-to: type=gha,mode=max,scope={project}-{release}
        push: true
        platforms: linux/amd64,linux/arm64
        build-args: 'RELEASE=xena

          PROJECT=nova

          PROJECT_REF=62e1a621d19e8833a18afdba86de7f8334171c63

          PROFILES=ceph openvswitch configdrive qemu migration

          DIST_PACKAGES=ovmf qemu-efi-aarch64

          PIP_PACKAGES='
        tags: quay.io/vexxhost/nova:62e1a621d19e8833a18afdba86de7f8334171c63
    - name: Build openstack/neutron
      uses: docker/build-push-action@v3.1.1
      with:
        context: images/openstack
        cache-from: type=gha,scope=neutron-xena
        cache-to: type=gha,mode=max,scope={project}-{release}
        push: true
        platforms: linux/amd64,linux/arm64
        build-args: 'RELEASE=xena

          PROJECT=neutron

          PROJECT_REF=74f127973831c9c5f889017b3b627bd9940e37a6

          PROFILES=openvswitch vpn

          DIST_PACKAGES=jq ethtool lshw

          PIP_PACKAGES=neutron-vpnaas'
        tags: quay.io/vexxhost/neutron:74f127973831c9c5f889017b3b627bd9940e37a6
    - name: Build openstack/monasca-notification
      uses: docker/build-push-action@v3.1.1
      with:
        context: images/openstack
        cache-from: type=gha,scope=monasca-notification-xena
        cache-to: type=gha,mode=max,scope={project}-{release}
        push: true
        platforms: linux/amd64
        build-args: 'RELEASE=xena

          PROJECT=monasca-notification

          PROJECT_REF=a94f013ff4addceb93ab556b666f63da7ea820e5

          PROFILES=

          DIST_PACKAGES=

          PIP_PACKAGES='
        tags: quay.io/vexxhost/monasca-notification:a94f013ff4addceb93ab556b666f63da7ea820e5
    - name: Build openstack/monasca-agent
      uses: docker/build-push-action@v3.1.1
      with:
        context: images/openstack
        cache-from: type=gha,scope=monasca-agent-xena
        cache-to: type=gha,mode=max,scope={project}-{release}
        push: true
        platforms: linux/amd64
        build-args: 'RELEASE=xena

          PROJECT=monasca-agent

          PROJECT_REF=284233aa9e53601548ae2ec435331b59974aa5a7

          PROFILES=

          DIST_PACKAGES=iproute2 libvirt-clients lshw

          PIP_PACKAGES=libvirt-python python-glanceclient python-neutronclient python-novaclient
          py3nvml'
        tags: quay.io/vexxhost/monasca-agent:284233aa9e53601548ae2ec435331b59974aa5a7
    - name: Build openstack/keystone
      uses: docker/build-push-action@v3.1.1
      with:
        context: images/openstack
        cache-from: type=gha,scope=keystone-xena
        cache-to: type=gha,mode=max,scope={project}-{release}
        push: true
        platforms: linux/amd64
        build-args: 'RELEASE=xena

          PROJECT=keystone

          PROJECT_REF=e772caa58ec7afdef4bd5fb58e44dc21a78c237b

          PROFILES=apache ldap openidc

          DIST_PACKAGES=

          PIP_PACKAGES='
        tags: quay.io/vexxhost/keystone:e772caa58ec7afdef4bd5fb58e44dc21a78c237b
    - name: Build openstack/horizon
      uses: docker/build-push-action@v3.1.1
      with:
        context: images/openstack
        cache-from: type=gha,scope=horizon-xena
        cache-to: type=gha,mode=max,scope={project}-{release}
        push: true
        platforms: linux/amd64
        build-args: 'RELEASE=xena

          PROJECT=horizon

          PROJECT_REF=48b702adf75b7f19420df578d2bf9bf813099af5

          PROFILES=apache

          DIST_PACKAGES=

          PIP_PACKAGES=designate-dashboard heat-dashboard ironic-ui magnum-ui neutron-vpnaas-dashboard
          octavia-dashboard senlin-dashboard monasca-ui'
        tags: quay.io/vexxhost/horizon:48b702adf75b7f19420df578d2bf9bf813099af5
    - name: Build openstack/monasca-api
      uses: docker/build-push-action@v3.1.1
      with:
        context: images/openstack
        cache-from: type=gha,scope=monasca-api-xena
        cache-to: type=gha,mode=max,scope={project}-{release}
        push: true
        platforms: linux/amd64
        build-args: 'RELEASE=xena

          PROJECT=monasca-api

          PROJECT_REF=44956801556b79c14373aa533df4debbd1da0ad9

          PROFILES=apache influxdb

          DIST_PACKAGES=

          PIP_PACKAGES='
        tags: quay.io/vexxhost/monasca-api:44956801556b79c14373aa533df4debbd1da0ad9
    - name: Build openstack/ironic
      uses: docker/build-push-action@v3.1.1
      with:
        context: images/openstack
        cache-from: type=gha,scope=ironic-xena
        cache-to: type=gha,mode=max,scope={project}-{release}
        push: true
        platforms: linux/amd64
        build-args: 'RELEASE=xena

          PROJECT=ironic

          PROJECT_REF=3f624e5caa83acf9b98443cf32cb0cd69143c6e2

          PROFILES=ipxe ipmi qemu tftp

          DIST_PACKAGES=ethtool lshw iproute2

          PIP_PACKAGES=python-dracclient sushy'
        tags: quay.io/vexxhost/ironic:3f624e5caa83acf9b98443cf32cb0cd69143c6e2
    - name: Build openstack/glance
      uses: docker/build-push-action@v3.1.1
      with:
        context: images/openstack
        cache-from: type=gha,scope=glance-xena
        cache-to: type=gha,mode=max,scope={project}-{release}
        push: true
        platforms: linux/amd64
        build-args: 'RELEASE=xena

          PROJECT=glance

          PROJECT_REF=cbe6522e67c2e437e600b4fb153a1d048a310282

          PROFILES=ceph

          DIST_PACKAGES=

          PIP_PACKAGES='
        tags: quay.io/vexxhost/glance:cbe6522e67c2e437e600b4fb153a1d048a310282
    - name: Build openstack/magnum
      uses: docker/build-push-action@v3.1.1
      with:
        context: images/openstack
        cache-from: type=gha,scope=magnum-xena
        cache-to: type=gha,mode=max,scope={project}-{release}
        push: true
        platforms: linux/amd64
        build-args: 'RELEASE=xena

          PROJECT=magnum

          PROJECT_REF=82a22387b91bb3c77261f42535be9c9d6b53a853

          PROFILES=

          DIST_PACKAGES=

          PIP_PACKAGES='
        tags: quay.io/vexxhost/magnum:82a22387b91bb3c77261f42535be9c9d6b53a853
    - name: Build openstack/monasca-persister
      uses: docker/build-push-action@v3.1.1
      with:
        context: images/openstack
        cache-from: type=gha,scope=monasca-persister-xena
        cache-to: type=gha,mode=max,scope={project}-{release}
        push: true
        platforms: linux/amd64
        build-args: 'RELEASE=xena

          PROJECT=monasca-persister

          PROJECT_REF=19d29bfab93206a7d7652037465d449895b7d8ce

          PROFILES=influxdb

          DIST_PACKAGES=

          PIP_PACKAGES='
        tags: quay.io/vexxhost/monasca-persister:19d29bfab93206a7d7652037465d449895b7d8ce
    - name: Build openstack/placement
      uses: docker/build-push-action@v3.1.1
      with:
        context: images/openstack
        cache-from: type=gha,scope=placement-xena
        cache-to: type=gha,mode=max,scope={project}-{release}
        push: true
        platforms: linux/amd64
        build-args: 'RELEASE=xena

          PROJECT=placement

          PROJECT_REF=f96984abd48f4d938d0fff0bab9b12ed933e320e

          PROFILES=apache

          DIST_PACKAGES=

          PIP_PACKAGES=httplib2'
        tags: quay.io/vexxhost/placement:f96984abd48f4d938d0fff0bab9b12ed933e320e
    - name: Promote openstack/cinder
      uses: akhilerm/tag-push-action@v2.0.0
      with:
        src: quay.io/vexxhost/cinder:b2caec7696817e02b0763d8b0d4f5d1b7f0b903e
        dst: quay.io/vexxhost/cinder:xena
    - name: Promote openstack/heat
      uses: akhilerm/tag-push-action@v2.0.0
      with:
        src: quay.io/vexxhost/heat:ead7cd61bd685ea46dd21c4ef3ea6b3fde273c10
        dst: quay.io/vexxhost/heat:xena
    - name: Promote openstack/senlin
      uses: akhilerm/tag-push-action@v2.0.0
      with:
        src: quay.io/vexxhost/senlin:28f8abc29a966d41f8b4502d1fc7432f86b14bea
        dst: quay.io/vexxhost/senlin:xena
    - name: Promote openstack/octavia
      uses: akhilerm/tag-push-action@v2.0.0
      with:
        src: quay.io/vexxhost/octavia:bda4d7160aebf7549d72b049c8dca53f7d4dedb5
        dst: quay.io/vexxhost/octavia:xena
    - name: Promote openstack/barbican
      uses: akhilerm/tag-push-action@v2.0.0
      with:
        src: quay.io/vexxhost/barbican:bb2779473f786f3bb7b84bc4f445089da8cbfe88
        dst: quay.io/vexxhost/barbican:xena
    - name: Promote openstack/designate
      uses: akhilerm/tag-push-action@v2.0.0
      with:
        src: quay.io/vexxhost/designate:410c1e8d60a6b3844050dd4d3ecc46f640356bfb
        dst: quay.io/vexxhost/designate:xena
    - name: Promote openstack/nova
      uses: akhilerm/tag-push-action@v2.0.0
      with:
        src: quay.io/vexxhost/nova:62e1a621d19e8833a18afdba86de7f8334171c63
        dst: quay.io/vexxhost/nova:xena
    - name: Promote openstack/neutron
      uses: akhilerm/tag-push-action@v2.0.0
      with:
        src: quay.io/vexxhost/neutron:74f127973831c9c5f889017b3b627bd9940e37a6
        dst: quay.io/vexxhost/neutron:xena
    - name: Promote openstack/monasca-notification
      uses: akhilerm/tag-push-action@v2.0.0
      with:
        src: quay.io/vexxhost/monasca-notification:a94f013ff4addceb93ab556b666f63da7ea820e5
        dst: quay.io/vexxhost/monasca-notification:xena
    - name: Promote openstack/monasca-agent
      uses: akhilerm/tag-push-action@v2.0.0
      with:
        src: quay.io/vexxhost/monasca-agent:284233aa9e53601548ae2ec435331b59974aa5a7
        dst: quay.io/vexxhost/monasca-agent:xena
    - name: Promote openstack/keystone
      uses: akhilerm/tag-push-action@v2.0.0
      with:
        src: quay.io/vexxhost/keystone:e772caa58ec7afdef4bd5fb58e44dc21a78c237b
        dst: quay.io/vexxhost/keystone:xena
    - name: Promote openstack/horizon
      uses: akhilerm/tag-push-action@v2.0.0
      with:
        src: quay.io/vexxhost/horizon:48b702adf75b7f19420df578d2bf9bf813099af5
        dst: quay.io/vexxhost/horizon:xena
    - name: Promote openstack/monasca-api
      uses: akhilerm/tag-push-action@v2.0.0
      with:
        src: quay.io/vexxhost/monasca-api:44956801556b79c14373aa533df4debbd1da0ad9
        dst: quay.io/vexxhost/monasca-api:xena
    - name: Promote openstack/ironic
      uses: akhilerm/tag-push-action@v2.0.0
      with:
        src: quay.io/vexxhost/ironic:3f624e5caa83acf9b98443cf32cb0cd69143c6e2
        dst: quay.io/vexxhost/ironic:xena
    - name: Promote openstack/glance
      uses: akhilerm/tag-push-action@v2.0.0
      with:
        src: quay.io/vexxhost/glance:cbe6522e67c2e437e600b4fb153a1d048a310282
        dst: quay.io/vexxhost/glance:xena
    - name: Promote openstack/magnum
      uses: akhilerm/tag-push-action@v2.0.0
      with:
        src: quay.io/vexxhost/magnum:82a22387b91bb3c77261f42535be9c9d6b53a853
        dst: quay.io/vexxhost/magnum:xena
    - name: Promote openstack/monasca-persister
      uses: akhilerm/tag-push-action@v2.0.0
      with:
        src: quay.io/vexxhost/monasca-persister:19d29bfab93206a7d7652037465d449895b7d8ce
        dst: quay.io/vexxhost/monasca-persister:xena
    - name: Promote openstack/placement
      uses: akhilerm/tag-push-action@v2.0.0
      with:
        src: quay.io/vexxhost/placement:f96984abd48f4d938d0fff0bab9b12ed933e320e
        dst: quay.io/vexxhost/placement:xena
